language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
addons:
  postgresql: '10.7'
services:
  - postgresql
before_script:
  - psql -c 'create database blockninjas_api_test;' -U postgres -W postgres
  - mix deps.get
script:
  - mix test