language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
addons:
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - psql -c 'create database blockninjas_api_test;' -U postgres
  - mix deps.get
script:
  - mix test